/**
 * Crimson Skies Static Recompilation — Register Model & Memory Access
 *
 * x86 registers are mapped to C global variables. Memory access uses
 * macros that translate through the original image base offset.
 *
 * Based on the proven pattern from XWA/Burnout3 recompilations.
 */

#ifndef RECOMP_TYPES_H
#define RECOMP_TYPES_H

#include <stdint.h>
#include <string.h>

/*========================================================================
 * Global Register Model
 *========================================================================*/

/* Volatile (caller-saved) registers */
extern uint32_t g_eax, g_ecx, g_edx, g_esp;

/* Callee-saved registers (preserved across RECOMP_CALL) */
extern uint32_t g_ebx, g_esi, g_edi;

/* FPU stack (simplified — single accumulator for most patterns) */
extern double g_st0, g_st1, g_st2, g_st3;
extern int g_fpu_top;

/* Flags (pattern-matched, not individually tracked) */
/* Condition codes are generated inline by the lifter */

/*========================================================================
 * Register Aliases
 *========================================================================*/

#define EAX g_eax
#define EBX g_ebx
#define ECX g_ecx
#define EDX g_edx
#define ESI g_esi
#define EDI g_edi
#define ESP g_esp

/* 16-bit aliases */
#define AX ((uint16_t)(g_eax & 0xFFFF))
#define BX ((uint16_t)(g_ebx & 0xFFFF))
#define CX ((uint16_t)(g_ecx & 0xFFFF))
#define DX ((uint16_t)(g_edx & 0xFFFF))

/* 8-bit aliases */
#define AL ((uint8_t)(g_eax & 0xFF))
#define AH ((uint8_t)((g_eax >> 8) & 0xFF))
#define BL ((uint8_t)(g_ebx & 0xFF))
#define BH ((uint8_t)((g_ebx >> 8) & 0xFF))
#define CL ((uint8_t)(g_ecx & 0xFF))
#define DL ((uint8_t)(g_edx & 0xFF))

/*========================================================================
 * Memory Access
 *========================================================================*/

/* Base address for memory-mapped original data sections */
extern uint8_t *g_mem_base;

/* Address translation: original VA → host pointer */
#define ADDR(va) ((uintptr_t)(g_mem_base + (va)))

/* Memory read/write at original virtual addresses */
#define MEM8(addr)  (*(volatile uint8_t  *)ADDR(addr))
#define MEM16(addr) (*(volatile uint16_t *)ADDR(addr))
#define MEM32(addr) (*(volatile uint32_t *)ADDR(addr))
#define MEMF32(addr) (*(volatile float   *)ADDR(addr))
#define MEMF64(addr) (*(volatile double  *)ADDR(addr))

/* Stack access */
#define STACK32(off) MEM32(g_esp + (off))

/*========================================================================
 * Function Dispatch
 *========================================================================*/

/* Dispatch table entry */
typedef struct {
    uint32_t address;       /* Original VA */
    void (*func)(void);     /* Recompiled C function */
} DispatchEntry;

extern DispatchEntry g_dispatch_table[];
extern int g_dispatch_count;

/* Call a recompiled function by original address */
#define RECOMP_CALL(addr) do { \
    uint32_t _save_ebx = g_ebx, _save_esi = g_esi, _save_edi = g_edi; \
    dispatch_call(addr); \
    g_ebx = _save_ebx; g_esi = _save_esi; g_edi = _save_edi; \
} while(0)

/* Indirect call (function pointer / vtable) */
#define RECOMP_ICALL(addr) do { \
    uint32_t _target = (addr); \
    uint32_t _save_ebx = g_ebx, _save_esi = g_esi, _save_edi = g_edi; \
    if (_target) dispatch_call(_target); \
    g_ebx = _save_ebx; g_esi = _save_esi; g_edi = _save_edi; \
} while(0)

void dispatch_call(uint32_t address);

/*========================================================================
 * Condition Macros (generated by lifter)
 *========================================================================*/

/* CMP-based conditions */
#define CMP_E(a, b)   ((a) == (b))
#define CMP_NE(a, b)  ((a) != (b))
#define CMP_B(a, b)   ((uint32_t)(a) < (uint32_t)(b))
#define CMP_AE(a, b)  ((uint32_t)(a) >= (uint32_t)(b))
#define CMP_A(a, b)   ((uint32_t)(a) > (uint32_t)(b))
#define CMP_BE(a, b)  ((uint32_t)(a) <= (uint32_t)(b))
#define CMP_L(a, b)   ((int32_t)(a) < (int32_t)(b))
#define CMP_GE(a, b)  ((int32_t)(a) >= (int32_t)(b))
#define CMP_G(a, b)   ((int32_t)(a) > (int32_t)(b))
#define CMP_LE(a, b)  ((int32_t)(a) <= (int32_t)(b))

/* TEST-based conditions (AND without storing result) */
#define TEST_Z(a, b)  (((a) & (b)) == 0)
#define TEST_NZ(a, b) (((a) & (b)) != 0)
#define TEST_S(a)     ((int32_t)(a) < 0)
#define TEST_NS(a)    ((int32_t)(a) >= 0)

#endif /* RECOMP_TYPES_H */
